#define TAP_CODE_DELAY 50
#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPING_FORCE_HOLD
#define QUICK_TAP_TERM 0

// Mouse definitions
#define  MK_COMBINED
#define MOUSEKEY_TIME_TO_MAX  60
