#pragma once

#undef PRODUCT
#define PRODUCT "Charybdis ursaw HW"


#undef  MATRIX_ROW_PINS
#define MATRIX_ROW_PINS { B6, F4, F5, F6, F7 }

#undef  MATRIX_COL_PINS
#define MATRIX_COL_PINS { B5, B4, E6, D7, C6, D4 }


#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD


/* Handedness. */
#undef  MASTER_RIGHT
#define MASTER_LEFT



#undef ROTATIONAL_TRANSFORM_ANGLE
#define ROTATIONAL_TRANSFORM_ANGLE 120

/*
#define CHARYBDIS_MINIMUM_DEFAULT_DPI     1200
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 400
#define CHARYBDIS_MINIMUM_SNIPING_DPI     200
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100
*/
