#pragma once

#undef PRODUCT
#define PRODUCT "Charybdis ursaw HW"


#undef  MATRIX_ROW_PINS
#define MATRIX_ROW_PINS { B6, F4, F5, F6, F7 }

#undef  MATRIX_COL_PINS
#define MATRIX_COL_PINS { B5, B4, E6, D7, C6, D4 }


#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

//#define CHARYBDIS_DRAGSCROLL_REVERSE_X
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
/* Handedness.*/
#define  MASTER_RIGHT




#undef ROTATIONAL_TRANSFORM_ANGLE
#define ROTATIONAL_TRANSFORM_ANGLE -65

/*
#define CHARYBDIS_MINIMUM_DEFAULT_DPI     1200
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 400
#define CHARYBDIS_MINIMUM_SNIPING_DPI     200
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100



#define BOOTMAGIC_LITE_ROW    0
#define BOOTMAGIC_LITE_COLUMN 0
#define BOOTMAGIC_LITE_ROW_RIGHT    5
#define BOOTMAGIC_LITE_COLUMN_RIGHT 0
*/
