
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
WPM_ENABLE = no

LEADER_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes


VPATH += keyboards/gboards
COMBO_ENABLE=yes
